# Root values.yaml for my-monitoring

# # Root chart's own settings (if any)
# replicaCount: 1
# image:
#   repository: nginx
#   tag: "latest"
#   pullPolicy: IfNotPresent

# Override Prometheus subchart values
prometheus:
  replicaCount: 1
  port: 9090
  image:
    repository: prom/prometheus
    tag: "v2.52.0"
  service:
    type: ClusterIP

# Override Grafana subchart values
grafana:
  replicaCount: 1
  image:
    repository: grafana/grafana
    tag: "9.0.0"
  service:
    type: ClusterIP
  ingress:
    enabled: false
  adminPassword: yourpasswordhere

# Common nodeSelector (example, optional)
nodeSelector: {}

postgresql:
  instances: 3
  version: "15"
  storage:
    size: 1Gi
    storageClass: standard