apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-grafana
  app: service-grafana
spec:
  selector:
    app: {{ .Release.Name }}-grafana
    name: grafana
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.port }}
      nodePort: {{ .Values.nodePort }}
