apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-prometheus
  labels:
    app: service-prometheus
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app: {{ .Release.Name }}-prometheus
  ports:
    - port: 80
      targetPort: {{ .Values.port }}
      {{- if eq (.Values.service.type | default "ClusterIP") "NodePort" }}
      nodePort: {{ .Values.service.nodePort | default 32001 }}
      {{- end }}
