apiVersion: v1
kind: Secret
metadata:
  name: my-app-user-password  # This name must match what you reference in pgsql-ha.yaml
  namespace: default         # Or your desired namespace, e.g., {{ .Release.Namespace }} if part of Helm
type: Opaque # Or 'kubernetes.io/tls' for TLS secrets, etc. 'Opaque' is standard for general secrets.
data:
  password: bWl4ZXI= # Replace this with the output from the 'base64' command