apiVersion: v1
kind: ConfigMap
metadata:
  name: my-monitoring-initdb-sql
  namespace: {{ .Release.Namespace }} # Use Helm's namespace here
data:
  # The key 'my_schema.sql' can be anything, but it's good to be descriptive
  my_schema.sql: |
    CREATE TABLE IF NOT EXISTS my_table (
      id SERIAL PRIMARY KEY,
      name VARCHAR(255) NOT NULL,
      description TEXT,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO my_app_user;
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO my_app_user;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO my_app_user;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO my_app_user;