apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Release.Name }}-pg-cluster
  namespace: {{ .Release.Namespace }}
spec:
  instances: {{ .Values.instances }}

  imageName: "quay.io/enterprisedb/postgresql:16.2"

  template:
    spec:
      securityContext:
        runAsUser: 26
        runAsGroup: 26
        fsGroup: 26

      initContainers:
        - name: fix-permissions
          image: busybox
          command:
            - sh
            - -c
            - |
              echo "Fixing permissions on /var/lib/postgresql/data ..."
              ls -ld /var/lib/postgresql/data
              mkdir -p /var/lib/postgresql/data/pgdata
              chown -R 26:26 /var/lib/postgresql/data
              echo "After fix:"
              ls -ld /var/lib/postgresql/data
              ls -ld /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
          securityContext:
            runAsUser: 0
            runAsGroup: 0

  storage:
    #existingClaim: {{ .Values.storage.existingClaim }}
    size: "{{ .Values.storage.size }}"
    storageClass: {{ .Values.storage.storageClass }}

  bootstrap:
    initdb:
      application:
        database: my_application_db
        owner: my_app_user
        secret:
          name: my-app-user-password
      dataChecksums: true
      postInitApplicationSQLRefs:
        configMapRefs:
          - name: my-monitoring-initdb-sql
            key: my_schema.sql
